CREATE TABLE EMP
(EMP_CODE      CHAR(5)        NOT NULL,
 EMP_NAME      CHAR(20)       NOT NULL,
 DEPT_CODE     CHAR(5)        NOT NULL 
                              CHECK
                               (DEPT_CODE > 0 AND DEPT_CODE < 6),
 DESIG_CODE    CHAR(5),
 SEX           CHAR(1),
 ADDRESS       CHAR(25),
 CITY          CHAR(25),
 STATE         CHAR(20),
 PIN           CHAR(6),
 BASIC         NUMBER(10,2),
 JN_DT         DATE,
 CONSTRAINT EMP_PK 
   PRIMARY KEY(EMP_CODE),
 CONSTRAINT EMP_DEPT_FK 
   FOREIGN KEY(DEPT_CODE) REFRENCES DEPARTMENT(DEPT_CODE) 

);


CREATE TABLE DESIGNATION
(DESIG_CODE    CHAR(5)         NOT NULL,
 DPET_NAME     CHAR(15),
 CONSTRAINT DESIG_PK 
    PRIMARY KEY(DESIG_CODE)
);

CREATE TABLE DEPARTMENT
(DEPT_CODE        CHAR(5)      NOT NULL,
 DEPT_NAME        CHAR(15),
 CONSTRAINT DEPT_PK
    PRIMARY KEY(DEPT_CODE)
);

DESC EMP;
DESC DESIGNATION;
DESC DEPARTMENT;
